version: "3.8"

services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.traefik.address=:8080"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.le.acme.email=benoit@bentoweb.fr"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - proxy
    # Traefik Dynamic configuration via Docker labels
    # labels:
    # Enable self‑routing
    # - "traefik.enable=true"

    # Dashboard router
    # - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.localhost`)"
    # - "traefik.http.routers.dashboard.entrypoints=websecure"
    # - "traefik.http.routers.dashboard.service=api@internal"
    # - "traefik.http.routers.dashboard.tls=true"

    # Basic‑auth middleware
    # - "traefik.http.middlewares.dashboard-auth.basicauth.users=<PASTE_HASH_HERE>"
    # - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

networks:
  proxy:
    external: true

  # Exemple de service nginx HTTPS
  # nginx-example:
  #   image: nginx:latest
  #   networks:
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.nginx-example.rule=Host(`example.com`)"
  #     - "traefik.http.routers.nginx-example.entrypoints=websecure"
  #     - "traefik.http.routers.nginx-example.tls=true"
  #     - "traefik.http.routers.nginx-example.tls.certresolver=le"
  #     # Configuration pour backend HTTPS
  #     - "traefik.http.services.nginx-example.loadbalancer.server.scheme=https"
  #     - "traefik.http.services.nginx-example.loadbalancer.server.port=443"
