version: "3.8"

services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.options=default@file"
      - "--providers.file.directory=/tls"
      - "--providers.file.watch=true"
      - "--entrypoints.traefik.address=:8080"
      - "--serversTransport.insecureSkipVerify=true"
      - "--certificatesresolvers.le.acme.email=benoit@bentoweb.fr"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./letsencrypt:/letsencrypt
      - ./tls.yaml:/tls/tls.yaml:ro
      - ./404.html:/usr/share/nginx/html/index.html:ro
    networks:
      - proxy

  # template 404 par défaut
  error-page:
    image: nginx:alpine
    container_name: error-page
    restart: unless-stopped
    volumes:
      - ./404.html:/usr/share/nginx/html/404.html:ro
      - ./404.html:/usr/share/nginx/html/index.html:ro
      - ./nginx-error.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error-page.rule=HostRegexp(`^.+$`)"
      - "traefik.http.routers.error-page.priority=1"
      - "traefik.http.routers.error-page.entrypoints=websecure"
      - "traefik.http.routers.error-page.tls=true"
      - "traefik.http.services.error-page.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
